Hi

In [172]:
import pandas as pd

In [173]:
import numpy as np

In [174]:
df = pd.read_csv(r"C:\Users\graem\OneDrive\Documents\Algonquin\Fall Semester\CST8504 - AI Techniques\dir\framingham_heart_study.csv")
df

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,1,39,4.0,0,0.0,0.0,0,0,0,195.0,106.0,70.0,26.97,80.0,77.0,0
1,0,46,2.0,0,0.0,0.0,0,0,0,250.0,121.0,81.0,28.73,95.0,76.0,0
2,1,48,1.0,1,20.0,0.0,0,0,0,245.0,127.5,80.0,25.34,75.0,70.0,0
3,0,61,3.0,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,65.0,103.0,1
4,0,46,3.0,1,23.0,0.0,0,0,0,285.0,130.0,84.0,23.10,85.0,85.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4235,0,48,2.0,1,20.0,NaN,0,0,0,248.0,131.0,72.0,22.00,84.0,86.0,0
4236,0,44,1.0,1,15.0,0.0,0,0,0,210.0,126.5,87.0,19.16,86.0,NaN,0
4237,0,52,2.0,0,0.0,0.0,0,0,0,269.0,133.5,83.0,21.47,80.0,107.0,0
4238,1,40,3.0,0,0.0,0.0,0,1,0,185.0,141.0,98.0,25.60,67.0,72.0,0
4239,0,39,3.0,1,30.0,0.0,0,0,0,196.0,133.0,86.0,20.91,85.0,80.0,0

In [222]:
import os

# Check current directory
print("Before:", os.getcwd())

Before: C:\Users\graem

In [223]:
# Set the new directory
os.chdir("C:\Users\graem\OneDrive\Documents\Algonquin\Fall Semester\CST8504 - AI Techniques\dir")

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (3039320248.py, line 2)

In [175]:
df.drop_duplicates()

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,1,39,4.0,0,0.0,0.0,0,0,0,195.0,106.0,70.0,26.97,80.0,77.0,0
1,0,46,2.0,0,0.0,0.0,0,0,0,250.0,121.0,81.0,28.73,95.0,76.0,0
2,1,48,1.0,1,20.0,0.0,0,0,0,245.0,127.5,80.0,25.34,75.0,70.0,0
3,0,61,3.0,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,65.0,103.0,1
4,0,46,3.0,1,23.0,0.0,0,0,0,285.0,130.0,84.0,23.10,85.0,85.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4235,0,48,2.0,1,20.0,NaN,0,0,0,248.0,131.0,72.0,22.00,84.0,86.0,0
4236,0,44,1.0,1,15.0,0.0,0,0,0,210.0,126.5,87.0,19.16,86.0,NaN,0
4237,0,52,2.0,0,0.0,0.0,0,0,0,269.0,133.5,83.0,21.47,80.0,107.0,0
4238,1,40,3.0,0,0.0,0.0,0,1,0,185.0,141.0,98.0,25.60,67.0,72.0,0
4239,0,39,3.0,1,30.0,0.0,0,0,0,196.0,133.0,86.0,20.91,85.0,80.0,0

In [176]:
df.isna().sum()

male                 0
age                  0
education          105
currentSmoker        0
cigsPerDay          29
BPMeds              53
prevalentStroke      0
prevalentHyp         0
diabetes             0
totChol             50
sysBP                0
diaBP                0
BMI                 19
heartRate            1
glucose            388
TenYearCHD           0
dtype: int64

To clean data - replace missing values of cigs/day for smokers
We replace value by average for smokers

In [177]:
smoker_avg = df.loc[df['currentSmoker'] == 1, 'cigsPerDay'].mean()

In [178]:
df.loc[(df['currentSmoker'] == 1) & (df['cigsPerDay'].isna()), 'cigsPerDay'] = smoker_avg

In [179]:
diabetes_G_avg = df.loc[df['diabetes'] == 1, 'glucose'].mean()
Non_diabetes_G_avg = df.loc[df['diabetes'] == 0, 'glucose'].mean()

In [180]:
df.loc[(df['diabetes'] == 1) & (df['glucose'].isna()), 'glucose'] = diabetes_G_avg
df.loc[(df['diabetes'] == 0) & (df['glucose'].isna()), 'glucose'] = Non_diabetes_G_avg

In [183]:
df

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,1,39,4.0,0,0.0,0.0,0,0,0,195.0,106.0,70.0,26.97,80.0,77.000000,0
1,0,46,2.0,0,0.0,0.0,0,0,0,250.0,121.0,81.0,28.73,95.0,76.000000,0
2,1,48,1.0,1,20.0,0.0,0,0,0,245.0,127.5,80.0,25.34,75.0,70.000000,0
3,0,61,3.0,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,65.0,103.000000,1
4,0,46,3.0,1,23.0,0.0,0,0,0,285.0,130.0,84.0,23.10,85.0,85.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4235,0,48,2.0,1,20.0,NaN,0,0,0,248.0,131.0,72.0,22.00,84.0,86.000000,0
4236,0,44,1.0,1,15.0,0.0,0,0,0,210.0,126.5,87.0,19.16,86.0,79.487323,0
4237,0,52,2.0,0,0.0,0.0,0,0,0,269.0,133.5,83.0,21.47,80.0,107.000000,0
4238,1,40,3.0,0,0.0,0.0,0,1,0,185.0,141.0,98.0,25.60,67.0,72.000000,0
4239,0,39,3.0,1,30.0,0.0,0,0,0,196.0,133.0,86.0,20.91,85.0,80.000000,0

In [184]:
age_edges = [0, 40, 50, 60, 1000]
age_labels = ['>= 40', '40-50', '50-60', '60+']

df['age_Group'] = pd.cut(
    df['age'],
    bins=age_edges,
    labels=age_labels,
    include_lowest=True
)

In [185]:
cigsPerDay_edges = [0, 1, 6, 16, 26, 1000]
cigsPerDay_labels = ['Zero', '1-5', '6-15', '16-25', '26+']

df['cigsPerDay_Group'] = pd.cut(
    df['cigsPerDay'],
    bins=cigsPerDay_edges,
    labels=cigsPerDay_labels,
    include_lowest=True
)

In [186]:
totChol_edges = [0, 200, 240, 300, 1000]
totChol_labels = ['Normal', 'Elevated', 'High', 'Very High']

df['totChol_Group'] = pd.cut(
    df['totChol'],
    bins=totChol_edges,
    labels=totChol_labels,
    include_lowest=True
)

In [187]:
sysBP_edges = [0, 120, 130, 140, 180, 300]
sysBP_labels = ['Normal', 'Elevated', 'Stage 1 High',
                'Stage 2 High', 'Severe']

df['sysBP_Group'] = pd.cut(
    df['sysBP'],
    bins=sysBP_edges,
    labels=sysBP_labels,
    include_lowest=True
)

In [188]:
diaBP_edges = [0, 80, 90, 120, 200]
diaBP_labels = ['Normal', 'Stage 1 High',
                'Stage 2 High', 'Severe']

df['diaBP_Group'] = pd.cut(
    df['diaBP'],
    bins=diaBP_edges,
    labels=diaBP_labels,
    include_lowest=True
)

In [189]:
BMI_edges = [0, 18.5, 25, 30, 35, 40, 100]
BMI_labels = ['Underweight', 'Normal', 'Overweight',
              'Obesity Class I', 'Obesity Class II',
              'Obesity Class III']

df['BMI_Group'] = pd.cut(
    df['BMI'],
    bins=BMI_edges,
    labels=BMI_labels,
    include_lowest=True
)

In [190]:
heartRate_edges = [0, 60, 100, 120, 300]
heartRate_labels = ['Low', 'Normal', 'Elevated', 'Very High']

df['heartRate_Group'] = pd.cut(
    df['heartRate'],
    bins=heartRate_edges,
    labels=heartRate_labels,
    include_lowest=True
)

In [191]:
glucose_edges = [0, 70, 100, 126, 200, 1000]
glucose_labels = ['Low', 'Normal', 'Prediabetic',
                  'Diabetic Range', 'Very High']

df['glucose_Group'] = pd.cut(
    df['glucose'],
    bins=glucose_edges,
    labels=glucose_labels,
    include_lowest=True
)

In [195]:
df

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,...,glucose,TenYearCHD,age_Group,cigsPerDay_Group,totChol_Group,sysBP_Group,diaBP_Group,BMI_Group,heartRate_Group,glucose_Group
0,1,39,4.0,0,0.0,0.0,0,0,0,195.0,...,77.000000,0,>= 40,Zero,Normal,Normal,Normal,Overweight,Normal,Normal
1,0,46,2.0,0,0.0,0.0,0,0,0,250.0,...,76.000000,0,40-50,Zero,High,Elevated,Stage 1 High,Overweight,Normal,Normal
2,1,48,1.0,1,20.0,0.0,0,0,0,245.0,...,70.000000,0,40-50,16-25,High,Elevated,Normal,Overweight,Normal,Low
3,0,61,3.0,1,30.0,0.0,0,1,0,225.0,...,103.000000,1,60+,26+,Elevated,Stage 2 High,Stage 2 High,Overweight,Normal,Prediabetic
4,0,46,3.0,1,23.0,0.0,0,0,0,285.0,...,85.000000,0,40-50,16-25,High,Elevated,Stage 1 High,Normal,Normal,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4235,0,48,2.0,1,20.0,NaN,0,0,0,248.0,...,86.000000,0,40-50,16-25,High,Stage 1 High,Normal,Normal,Normal,Normal
4236,0,44,1.0,1,15.0,0.0,0,0,0,210.0,...,79.487323,0,40-50,6-15,Elevated,Elevated,Stage 1 High,Normal,Normal,Normal
4237,0,52,2.0,0,0.0,0.0,0,0,0,269.0,...,107.000000,0,50-60,Zero,High,Stage 1 High,Stage 1 High,Normal,Normal,Prediabetic
4238,1,40,3.0,0,0.0,0.0,0,1,0,185.0,...,72.000000,0,>= 40,Zero,Normal,Stage 2 High,Stage 2 High,Overweight,Normal,Normal
4239,0,39,3.0,1,30.0,0.0,0,0,0,196.0,...,80.000000,0,>= 40,26+,Normal,Stage 1 High,Stage 1 High,Normal,Normal,Normal

In [196]:
df.isna().sum()

male                  0
age                   0
education           105
currentSmoker         0
cigsPerDay            0
BPMeds               53
prevalentStroke       0
prevalentHyp          0
diabetes              0
totChol              50
sysBP                 0
diaBP                 0
BMI                  19
heartRate             1
glucose               0
TenYearCHD            0
age_Group             0
cigsPerDay_Group      0
totChol_Group        50
sysBP_Group           0
diaBP_Group           0
BMI_Group            19
heartRate_Group       1
glucose_Group         0
dtype: int64

In [198]:
df['totChol_Group'] = df['totChol_Group'].cat.add_categories("Not Known")
df['BMI_Group'] = df['BMI_Group'].cat.add_categories("Not Known")
df['heartRate_Group'] = df['heartRate_Group'].cat.add_categories("Not Known")

In [199]:
df = df.fillna("Not Known")

In [200]:
df.isna().sum()

male                0
age                 0
education           0
currentSmoker       0
cigsPerDay          0
BPMeds              0
prevalentStroke     0
prevalentHyp        0
diabetes            0
totChol             0
sysBP               0
diaBP               0
BMI                 0
heartRate           0
glucose             0
TenYearCHD          0
age_Group           0
cigsPerDay_Group    0
totChol_Group       0
sysBP_Group         0
diaBP_Group         0
BMI_Group           0
heartRate_Group     0
glucose_Group       0
dtype: int64

In [205]:
dfClean = df.iloc[:, [15,0,1,2,3,5,6,7,8,16,17,18,19,20,21,22,23]].copy()

In [209]:
encoded_df = pd.get_dummies(dfClean, dtype=int)
encoded_df

,TenYearCHD,male,age,currentSmoker,prevalentStroke,prevalentHyp,diabetes,education_1.0,education_2.0,education_3.0,...,heartRate_Group_Low,heartRate_Group_Normal,heartRate_Group_Elevated,heartRate_Group_Very High,heartRate_Group_Not Known,glucose_Group_Low,glucose_Group_Normal,glucose_Group_Prediabetic,glucose_Group_Diabetic Range,glucose_Group_Very High
0,0,1,39,0,0,0,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
1,0,0,46,0,0,0,0,0,1,0,...,0,1,0,0,0,0,1,0,0,0
2,0,1,48,1,0,0,0,1,0,0,...,0,1,0,0,0,1,0,0,0,0
3,1,0,61,1,0,1,0,0,0,1,...,0,1,0,0,0,0,0,1,0,0
4,0,0,46,1,0,0,0,0,0,1,...,0,1,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4235,0,0,48,1,0,0,0,0,1,0,...,0,1,0,0,0,0,1,0,0,0
4236,0,0,44,1,0,0,0,1,0,0,...,0,1,0,0,0,0,1,0,0,0
4237,0,0,52,0,0,0,0,0,1,0,...,0,1,0,0,0,0,0,1,0,0
4238,0,1,40,0,0,1,0,0,0,1,...,0,1,0,0,0,0,1,0,0,0
4239,0,0,39,1,0,0,0,0,0,1,...,0,1,0,0,0,0,1,0,0,0

In [211]:
encoded_df.isna().sum()

TenYearCHD                      0
male                            0
age                             0
currentSmoker                   0
prevalentStroke                 0
prevalentHyp                    0
diabetes                        0
education_1.0                   0
education_2.0                   0
education_3.0                   0
education_4.0                   0
education_Not Known             0
BPMeds_0.0                      0
BPMeds_1.0                      0
BPMeds_Not Known                0
age_Group_>= 40                 0
age_Group_40-50                 0
age_Group_50-60                 0
age_Group_60+                   0
cigsPerDay_Group_Zero           0
cigsPerDay_Group_1-5            0
cigsPerDay_Group_6-15           0
cigsPerDay_Group_16-25          0
cigsPerDay_Group_26+            0
totChol_Group_Normal            0
totChol_Group_Elevated          0
totChol_Group_High              0
totChol_Group_Very High         0
totChol_Group_Not Known         0
sysBP_Group_Normal              0
sysBP_Group_Elevated            0
sysBP_Group_Stage 1 High        0
sysBP_Group_Stage 2 High        0
sysBP_Group_Severe              0
diaBP_Group_Normal              0
diaBP_Group_Stage 1 High        0
diaBP_Group_Stage 2 High        0
diaBP_Group_Severe              0
BMI_Group_Underweight           0
BMI_Group_Normal                0
BMI_Group_Overweight            0
BMI_Group_Obesity Class I       0
BMI_Group_Obesity Class II      0
BMI_Group_Obesity Class III     0
BMI_Group_Not Known             0
heartRate_Group_Low             0
heartRate_Group_Normal          0
heartRate_Group_Elevated        0
heartRate_Group_Very High       0
heartRate_Group_Not Known       0
glucose_Group_Low               0
glucose_Group_Normal            0
glucose_Group_Prediabetic       0
glucose_Group_Diabetic Range    0
glucose_Group_Very High         0
dtype: int64

Now we do the 70-15-15 split

In [214]:
from sklearn.model_selection import train_test_split

# Split into training (70%) and temporary (30%) groups
train, temp = train_test_split(
    encoded_df,
    test_size=0.30,
    random_state=42
)

# Split temporary into validation (15%) and testing (15%)
validation, test = train_test_split(
    temp,
    test_size=0.50,
    random_state=42
)

In [215]:
train

,TenYearCHD,male,age,currentSmoker,prevalentStroke,prevalentHyp,diabetes,education_1.0,education_2.0,education_3.0,...,heartRate_Group_Low,heartRate_Group_Normal,heartRate_Group_Elevated,heartRate_Group_Very High,heartRate_Group_Not Known,glucose_Group_Low,glucose_Group_Normal,glucose_Group_Prediabetic,glucose_Group_Diabetic Range,glucose_Group_Very High
4097,0,1,54,1,0,0,0,0,1,0,...,0,1,0,0,0,0,1,0,0,0
3165,0,1,44,1,0,0,0,0,0,1,...,0,1,0,0,0,0,1,0,0,0
2499,1,0,46,1,0,0,0,0,1,0,...,0,1,0,0,0,1,0,0,0,0
3345,0,1,38,1,0,0,0,0,1,0,...,1,0,0,0,0,0,1,0,0,0
3596,0,1,40,1,0,0,0,0,1,0,...,1,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3444,0,0,36,1,0,1,0,1,0,0,...,0,1,0,0,0,0,1,0,0,0
466,0,0,57,1,0,0,0,0,0,1,...,0,1,0,0,0,0,1,0,0,0
3092,0,0,60,0,0,1,0,0,1,0,...,0,1,0,0,0,0,1,0,0,0
3772,0,1,39,1,0,0,0,0,1,0,...,0,1,0,0,0,1,0,0,0,0
860,0,0,35,0,0,0,0,0,1,0,...,0,1,0,0,0,0,1,0,0,0

In [216]:
test

,TenYearCHD,male,age,currentSmoker,prevalentStroke,prevalentHyp,diabetes,education_1.0,education_2.0,education_3.0,...,heartRate_Group_Low,heartRate_Group_Normal,heartRate_Group_Elevated,heartRate_Group_Very High,heartRate_Group_Not Known,glucose_Group_Low,glucose_Group_Normal,glucose_Group_Prediabetic,glucose_Group_Diabetic Range,glucose_Group_Very High
1662,0,0,54,1,0,1,0,1,0,0,...,0,1,0,0,0,0,1,0,0,0
1912,0,0,47,0,0,0,0,1,0,0,...,0,1,0,0,0,0,1,0,0,0
3407,1,1,44,1,0,0,0,1,0,0,...,0,1,0,0,0,0,1,0,0,0
543,1,1,47,1,0,1,0,0,1,0,...,0,1,0,0,0,0,1,0,0,0
1779,1,1,43,1,0,0,0,0,0,0,...,0,1,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3192,0,0,43,1,0,0,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
33,1,1,61,1,0,0,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
2948,0,1,54,0,0,0,0,1,0,0,...,0,1,0,0,0,0,1,0,0,0
1392,0,0,45,1,0,0,0,0,1,0,...,0,1,0,0,0,1,0,0,0,0
1474,0,0,47,0,0,0,0,1,0,0,...,0,1,0,0,0,1,0,0,0,0

In [218]:
validation

,TenYearCHD,male,age,currentSmoker,prevalentStroke,prevalentHyp,diabetes,education_1.0,education_2.0,education_3.0,...,heartRate_Group_Low,heartRate_Group_Normal,heartRate_Group_Elevated,heartRate_Group_Very High,heartRate_Group_Not Known,glucose_Group_Low,glucose_Group_Normal,glucose_Group_Prediabetic,glucose_Group_Diabetic Range,glucose_Group_Very High
1210,0,1,52,0,0,0,0,1,0,0,...,0,1,0,0,0,1,0,0,0,0
2297,0,1,54,1,0,0,0,0,0,0,...,0,1,0,0,0,1,0,0,0,0
3780,0,0,64,1,0,1,0,0,1,0,...,0,1,0,0,0,0,1,0,0,0
1477,0,0,49,0,0,0,0,0,1,0,...,0,1,0,0,0,0,1,0,0,0
314,0,0,39,0,0,0,0,0,1,0,...,0,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1220,0,0,43,0,0,0,0,0,0,1,...,0,1,0,0,0,0,1,0,0,0
2351,0,0,64,0,0,0,0,0,0,1,...,0,1,0,0,0,0,1,0,0,0
0,0,1,39,0,0,0,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
573,1,0,63,0,0,1,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
2697,0,0,56,0,0,1,0,1,0,0,...,0,1,0,0,0,0,1,0,0,0

We now have 3 dataframe to use for Training, testing and validating

In [219]:
test.to_csv('test.csv', index=True)
train.to_csv('train.csv', index=True)
validation.to_csv('validation.csv', index=True)